### ISSUE TITLE
Cannot logout from all sessions

### ISSUE THREAD

**Issue by datanchor** [auth0-samples/auth0-android-sample#89]
Currently, we are using auth0 for authentication for our mobile apps(Android and iOS). We noticed that after a user has performed log out they are not being requested for username/password next time. We followed https://auth0.com/docs/quickstart/native/android/03-session-handling#log-out to implement login and logout. The user logs out of the app, but when he logs back in he is not prompted to enter a username and password. We want them to be able to log out of all sessions. We even tried to use the federated logout option, that did not help either. I can provide further details if needed to help us with this.

**Comment by undermark5** [comment]
Sounds like you are failing to clear the credentials from the security credential manager. Just what I'm theorizing based on what little I know. The application lifecycle is important to understand as well, if you don't finish the activity where the user is logged in, it is possible to return to it in a logged out state. Make sure that you are both clearing the credentials manager as well as returning the user to the login activity after logging out (whichever activity triggers the login flow to begin).

**Comment by dkumaryadav** [comment]
Hi,

I am a developer working on the above code base, so here are few more details how the login, logout  flow is

==> Login

	1. User sees screen to enter domain, on enterning valid domain user is redirect to auth0 login screen
	2. In auth0 login screen user selects login with Azure and then on the next screen user is asked to enter valid username / password.
	3. On entering valid username and password, user is navigated to application specific screen and the authentication activity is cleared from the application stack so that user cannot not navigate back to the login screen.

==> Logout and Login again(problem here)

	1. From the application screen user selects to logout
	2. We call _credentialsManager.clearCredentials()_ to remove user creds and user is shown the login screen.
	3. Now, the user can enter domain information on enetering valid domain the user is redirect to auth0 login screen
	4. In auth0 login screen user selects login with Azure, here the user is not being asked to enter his username / password and it authenticates the user with the creds which he entered the first time to authenticate

So, we wanted to know what additional steps we need to add in our login / logout flow so that the user is being asked to enter username / password so that he has the flexibility of using multiple username and passwords.

**Comment by undermark5** [comment]
So to me it sounds like an issue with azure not auth0. I'm not a dev for auth0, but from what it seems like to me is that there is a cookie that the browser is using that is keeping the user logged in to azure and since the azure login redirect results in the user automatically logging in, it doesn't prompt for the account information again. I would expect there is a way to prevent these cookies from being stored, but I'm unsure as to how you would do that.

I also could be very far off on the cause of the issue, but I get similar behavior when I'm signed in with GitHub, it doesn't ask me to sign into GitHub unless I'm not currently signed in according to the cookies. Your logout flow either needs to clear that cookie, or trigger a logout from azure as well.

**Comment by dkumaryadav** [comment]
Yes, we also assumed this could be because of the cookies stored in the browser which auth0 uses to login. Based on our research we found this doc(https://auth0.com/docs/logout/guides/logout-idps) which says we can redirect the user to "federated" logout URL to log user out of Identity providers. 

So, after clearing creds from credential manager we navigate the user to the "federated" URL using chrome custom tabs but still we are facing the same issue where username / password is not being asked when we try to login.

**Comment by undermark5** [comment]
Quickly reading those docs seems that you should be using the "federated" URL as the audience to go through the auth0 logout flow before clearing the credentials. If this is what you are doing, it might be a worthwhile experiment to try manually clearing the cookies and see if that is indeed the issue. If this still does not work, I would recommend getting in touch with support rather than using the GitHub issues (doesn't seem like they are monitored very well or don't have the resources to do so at this time) via a support ticket (looks like it is for paying subscribers only) https://support.auth0.com/tickets/new or by asking in the community pages https://community.auth0.com/

**Comment by dkumaryadav** [comment]
I noticed that we can use "withAudience" in the login call we make using WebAuthProvider. However, this is not present in the logout.  Refer below screen snip. 
<img width="576" alt="Screen Shot 2020-07-08 at 1 00 53 PM" src="https://user-images.githubusercontent.com/20942306/86954131-0fb4b400-c11b-11ea-85bd-d686b41f8786.png">

**Comment by undermark5** [comment]
I'm not a maintainer for this project. It doesn't appear that any of the auth0 team even actively monitors this page. You will be better off getting support from the methods listed above. If you are paying for the services you can make a ticket, if you are not, the community pages are your best bet. I'm just a guy trying to be helpful but I cannot provide any further assistance unless I explicitly take time out of my normal work schedule. The last thing that I can offer up is to set the returnToUrl to the federated URL (https://YOUR_DOMAIN/v2/logout?federated). You will also need to add that to your allowed logout callback URLs in your auth0 application configuration.

Again, you will get better support using one of the other channels mentioned previously. I want to help people, but I'm not a maintainer nor am I an auth0 expert. If I didn't have other commitments then I would continue to dig and help further, but unfortunately right now that is not the case.

**Comment by dkumaryadav** [comment]
Hello @undermark5,

Thanks for your support and inputs. We saw that a similar question has been raised in the community using that we are following up with an auth0 expert and hope we some get more inputs that we can use to resolve this issue.

**FYR**: https://community.auth0.com/t/logout-of-auth0-does-not-log-my-user-out-of-facebook-azure/44447

Thanks,
Deepak
